# ---- Builder Stage ----
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---- Production Stage ----
FROM node:20-alpine
WORKDIR /app
# Buat pengguna non-root
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Salin hanya artifact yang diperlukan
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY .env.docker ./.env

# Pastikan Prisma client sudah digenerate
RUN npx prisma generate

EXPOSE 3000
CMD ["node", "dist/main"]